/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OlAmbulanceWlList {
    }
}
declare global {
    interface HTMLOlAmbulanceWlListElement extends Components.OlAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLOlAmbulanceWlListElement: {
        prototype: HTMLOlAmbulanceWlListElement;
        new (): HTMLOlAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "ol-ambulance-wl-list": HTMLOlAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface OlAmbulanceWlList {
    }
    interface IntrinsicElements {
        "ol-ambulance-wl-list": OlAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ol-ambulance-wl-list": LocalJSX.OlAmbulanceWlList & JSXBase.HTMLAttributes<HTMLOlAmbulanceWlListElement>;
        }
    }
}
